services:
  spa:
    build:
      dockerfile: front-end.Dockerfile
      args:
        - AnalyticsServicePort=${AnalyticsServicePort}
    image: hackmotion-spa
    container_name: hackmotion-spa
    restart: unless-stopped
    working_dir: /var/hackmotion
    ports:
      - ${FrontEndPort}:4000
    networks:
      - hackmotion
  analytics:
    build:
      dockerfile: back-end.Dockerfile
    image: hackmotion-analytics
    container_name: hackmotion-analytics
    restart: unless-stopped
    working_dir: /var/hackmotion
    ports:
      - ${AnalyticsServicePort}:8080
    networks:
      - hackmotion
networks:
  hackmotion:
    driver: bridge